services:
    nodejs-server:
        image: sameerbhagtani/devops-cohort
        deploy:
            replicas: 5
        networks:
            - chaicode-internal

    caddy:
        image: caddy:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - chaicode-internal

networks:
    chaicode-internal:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:
